# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatstodo_ml_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63hatstodo_ml_service.proto\x12\x14\x63hatstodo_ml_service\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\x0fUserChatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cmessage_text\x18\x03 \x03(\t\"\x85\x01\n\x14\x43hatAnalysisResponse\x12\x0e\n\x06userID\x18\x01 \x01(\x03\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07summary\x18\x03 \x03(\t\x12\r\n\x05tasks\x18\x04 \x03(\t\x12\x0e\n\x06\x65vents\x18\x05 \x03(\t2y\n\x13\x43hatAnalysisService\x12\x62\n\x0b\x41nalyzeChat\x12%.chatstodo_ml_service.UserChatRequest\x1a*.chatstodo_ml_service.ChatAnalysisResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatstodo_ml_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERCHATREQUEST']._serialized_start=85
  _globals['_USERCHATREQUEST']._serialized_end=188
  _globals['_CHATANALYSISRESPONSE']._serialized_start=191
  _globals['_CHATANALYSISRESPONSE']._serialized_end=324
  _globals['_CHATANALYSISSERVICE']._serialized_start=326
  _globals['_CHATANALYSISSERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
